Only check for default_kernel is no value - rhbz#2293047

diff --git a/akmods b/akmods
--- a/akmods
+++ b/akmods
@@ -185,27 +185,6 @@ init ()
 		}
 	fi
 
-	# ensure to build for grub or systemd-boot default kernel
-	#
-	# IMPORTANT: "bootctl is-installed" check that systemd-boot is installed only.
-	# It doesn't check if systemd-boot is the default loader.
-	# So we assume grubby results if available
-	if [ ! -h /usr/sbin/grubby ] &&  command -v grubby >/dev/null 2>&1 ; then
-		default_kernel=$(grubby --default-kernel | sed -e 's/^.*vmlinuz-//')
-	elif bootctl is-installed >/dev/null 2>&1 ; then
-		# Leave jq as optional - isDefault requires systemd 253
-		if command -v jq >/dev/null ; then
-			default_kernel="$(bootctl list  --json=short | jq -r '.[] | select(.isDefault).version')"
-		fi
-	else # They use neither systemd-boot nor grub2
-		echo -n "Unable to figure out the default kernel" >&2
-		echo_warning ; echo
-		default_kernel=""
-	fi
-	if ! $(echo "${kernels}" | grep -q "${default_kernel}") ; then
-		kernels="${kernels} ${default_kernel}"
-	fi
-
 	# needs root permissions
 	if [[ ! -w /var ]] ; then
 		echo -n "Needs to run as root to be able to install rpms." >&2
@@ -248,6 +227,51 @@ init ()
 	# create lockfile and wait till we get it
 	exec 99>/run/akmods/akmods.lock
 	flock -w 900 99
+}
+
+
+check_kernel_devel()
+{
+	if [[ ! -r /usr/src/kernels/"${1}"/Makefile ]] && \
+		 [[ ! -r /lib/modules/"${1}"/build/Makefile ]] ; then
+		echo "Could not find files needed to compile modules for ${1}"
+		echo "Are the development files for kernel ${1} or the appropriate kernel-devel package installed?"
+		exit 1
+	elif [[ -r /usr/src/kernels/"${1}"/Makefile ]] && \
+		 [[ ! -d /lib/modules/"${1}" ]] ; then
+		# this is a red hat / fedora kernel-devel package, but the kernel for it is not installed
+		# kmodtool would add a dep on that kernel when building; thus when we'd try to install the
+		# rpms we'd run into a missing-dep problem. Thus we prevent that case
+		echo "Kernel ${1} not installed"
+		exit 1
+	fi
+}
+
+check_default_kernel()
+{
+	# Ensure to build for grub or systemd-boot default kernel
+	#
+	# IMPORTANT: "bootctl is-installed" check that systemd-boot is installed only.
+	# It doesn't check if systemd-boot is the default loader.
+	# So we assume grubby results if available
+	if [ ! -h /usr/sbin/grubby ] &&  command -v grubby >/dev/null 2>&1 ; then
+		default_kernel=$(grubby --default-kernel | sed -e 's/^.*vmlinuz-//')
+	elif bootctl is-installed >/dev/null 2>&1 ; then
+		# Leave jq as optional - isDefault requires systemd 253
+		if command -v jq >/dev/null ; then
+			default_kernel="$(bootctl list  --json=short | jq -r '.[] | select(.isDefault).version')"
+		fi
+	else # They use neither systemd-boot nor grub2
+		echo -n "Unable to figure out the default kernel" >&2
+		echo_warning ; echo
+		default_kernel=""
+	fi
+
+	check_kernel_devel "${default_kernel}"
+
+	if ! $(echo "${kernels}" | grep -q "${default_kernel}") ; then
+		kernels="${kernels} ${default_kernel}"
+	fi
 }
 
 buildinstall_kmod()
@@ -514,19 +538,10 @@ while [ "${1}" ] ; do
 			if [[ ! -n "${1}" ]] ; then
 				echo "ERROR: Please provide the kernel-version to build for together with --kernel" >&2
 				exit 1
-			elif [[ ! -r /usr/src/kernels/"${1}"/Makefile ]] && \
-				 [[ ! -r /lib/modules/"${1}"/build/Makefile ]] ; then
-				echo "Could not find files needed to compile modules for ${1}"
-				echo "Are the development files for kernel ${1} or the appropriate kernel-devel package installed?"
-				exit 1
-			elif [[ -r /usr/src/kernels/"${1}"/Makefile ]] && \
-				 [[ ! -d /lib/modules/"${1}" ]] ; then
-				# this is a red hat / fedora kernel-devel package, but the kernel for it is not installed
-				# kmodtool would add a dep on that kernel when building; thus when we'd try to install the
-				# rpms we'd run into a missing-dep problem. Thus we prevent that case
-				echo "Kernel ${1} not installed"
-				exit 1
 			fi
+
+			check_kernel_devel "${1}"
+
 			# overwrites the default:
 			if [[ ! -n "${kernels}" ]] ; then
 				kernels="${1}"
@@ -599,6 +614,11 @@ done
 
 # sanity checks
 init
+
+# only check for default_kernel if no value have been parsed
+if  [ -z ${kernels} ] ; then
+	check_default_kernel
+fi
 
 # go
 for kernel in ${kernels} ; do
