Added support for combined single-letter arguments + Chowned symlinks.

diff --git a/akmods-kmodgenca b/akmods-kmodgenca
--- a/akmods-kmodgenca
+++ b/akmods-kmodgenca
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # NAME: 'kmodgenca'
-# PURPOSE: Helper script to create CA/Keypair to sign modules.
+# PURPOSE: Helper script to create CA/key pair to sign modules.
 # Copyright (c) 2017 Stanislas Leduc <stanislas.leduc@balinor.net>
 # Copyright (c) 2018-2019 Nicolas Viéville <nicolas.vieville@uphf.fr>
 # Copyright (c) 2024 Rohan Barar <rohan.barar@gmail.com>
@@ -28,9 +28,9 @@
 
 # EXIT STATUS LOOKUP
 # 0 - SUCCESS
-# 1 - INVALID ARGUMENT
+# 1 - INVALID COMMAND LINE ARGUMENT
 # 2 - BROKEN EXISTING KEY PAIR
-# 3 - CA CERT CONFIG MODIFICATION FAILED
+# 3 - CA CERTIFICATE CONFIGURATION MODIFICATION FAILED
 
 # DECLARE CONSTANTS
 # Script Information
@@ -67,10 +67,12 @@ KEY_SUFFIX="$(date "+%F_%T_%N")"
 # FUNCTIONS
 function help() {
     echo "Creates a Certificate Authority (CA) and key pair for module signing."
+    echo "Private keys are created in:               '${PRIVATE_KEY_DIR}'."
+    echo "Public keys (certificates) are created in: '${PUBLIC_KEY_DIR}'."
     echo -e "\nUsage: ${SCRIPT_NAME} [OPTIONS]"
     echo -e "\nOptions:"
     echo "  -a, --auto           Utilise default values for 'cacert.config'."
-    echo "  -f, --force          Create CA/Keypair even if one already exists."
+    echo "  -f, --force          Create CA/key pair even if one already exists."
     echo "  -h, --help           Display this help message."
     echo "  -V, --version        Display script version information."
 }
@@ -94,13 +96,45 @@ function parse_arguments() {
             echo "${SCRIPT_NAME} v${SCRIPT_VERSION}"
             exit 0
             ;;
+        -*)
+            # Handle combined single-letter options.
+            for (( i=1; i<${#1}; i++ )); do
+                case "${1:$i:1}" in
+                a)
+                    AUTOMATIC_BUILD=1
+                    ;;
+                f)
+                    FORCE_BUILD=1
+                    ;;
+                h)
+                    help
+                    exit 0
+                    ;;
+                V)
+                    echo "${SCRIPT_NAME} v${SCRIPT_VERSION}"
+                    exit 0
+                    ;;
+                *)
+                    echo -e "${BOLD_RED_TEXT}ERROR:${CLEAR_TEXT} INVALID OPTION '${1}'.\n" >&2
+                    help >&2
+                    exit 1
+                    ;;
+                esac
+            done
+            shift
+            ;;
         *)
-            echo -e "${BOLD_RED_TEXT}ERROR:${CLEAR_TEXT} INVALID OPTION '${1}'." >&2
+            echo -e "${BOLD_RED_TEXT}ERROR:${CLEAR_TEXT} INVALID OPTION '${1}'.\n" >&2
             help >&2
             exit 1
             ;;
         esac
     done
+
+    # Warn user.
+    if [[ "$FORCE_BUILD" -eq 1 ]]; then
+        echo -e "${BOLD_YELLOW_TEXT}WARNING:${CLEAR_TEXT} FORCED BUILD SELECTED. MOK OVERWRITE MAY OCCUR!"
+    fi
 }
 
 function check_broken_key_pair() {
@@ -108,6 +142,7 @@ function check_broken_key_pair() {
     #   1. A certificate (public key) OR private key exists (but not both), AND
     #   2. A forced rebuild was not requested (i.e., 'FORCE_BUILD' is NOT '1')
 
+    # Note: This approach will also detect broken symlinks (i.e., return 0).
     # shellcheck disable=SC2155
     local pub_key_exists=$(sudo readlink -e "$PUBLIC_KEY_PATH" &>/dev/null && echo 1 || echo 0)
 
@@ -133,6 +168,8 @@ function check_existing_key_pair() {
     # Terminate the script when:
     #   1. Both a certificate (public key) and private key already exist, AND
     #   2. A forced rebuild was not requested (i.e., 'FORCE_BUILD' is NOT '1')
+
+    # Note: This approach will return '1' in the event of a broken symlink.
     if sudo readlink -e "$PUBLIC_KEY_PATH" &>/dev/null && \
         sudo readlink -e "$PRIVATE_KEY_PATH" &>/dev/null && \
         [ "$FORCE_BUILD" -eq 0 ]; then
@@ -153,13 +190,13 @@ function create_ca_cert_config() {
         # Set '-batch' argument.
         AUTOMATIC_BUILD_OPTION="-batch"
 
-		# Initialise output variable.
-		local sed_output=""
+        # Initialise output variable.
+        local sed_output=""
 
         # Utilise default values if 'AUTOMATIC_BUILD' is equal to '1'.
         # Set OpenSSL field values.
         # Comment default and min/max values.
-		sed_output=$(sudo sed -e "s#\(0.organizationName *= \).*#\1$(hostname)#" \
+        sed_output=$(sudo sed -e "s#\(0.organizationName *= \).*#\1$(hostname)#" \
             -e "s#\(organizationalUnitName *= \).*#\1$(hostname)#" \
             -e "s#\(emailAddress *= \).*#\1akmods@$(hostname)#" \
             -e "s#\(localityName *= \).*#\1None#" \
@@ -176,9 +213,9 @@ function create_ca_cert_config() {
     fi
 
     # Check if 'sed' command failed.
-	# shellcheck disable=SC2181
+    # shellcheck disable=SC2181
     if [ "$?" -ne 0 ]; then
-		echo "$sed_output"
+        echo "$sed_output"
         echo -e "${BOLD_RED_TEXT}ERROR:${CLEAR_TEXT} CACERT CONFIG FILE MODIFICATION FAILED."
         echo "Failed to update the CA certificate configuration file at '${CACERT_CONFIG_PATH}'."
         echo "Quitting."
@@ -190,27 +227,27 @@ function backup_existing_key_pair() {
     # Check if the randomly-generated key pair name conflicts with an existing pair.
     if [[ -e "${PUBLIC_KEY_DIR}/${KEYNAME}.der" ]] ; then
         # If the public key (certificate) has already been enrolled in the UEFI, append "_enrolled" to the suffix of the backup file.
-		# As per 'mokutil/src/mokutil.c' @ https://src.fedoraproject.org/rpms/mokutil.git:
-		#    -1 (255) : General Error.
-		#     0       : Key Not Enrolled.
-		#     1       : Key Enrolled.
+        # As per 'mokutil/src/mokutil.c' @ https://src.fedoraproject.org/rpms/mokutil.git:
+        #    -1 (255) : General Error.
+        #     0       : Key Not Enrolled.
+        #     1       : Key Enrolled.
         # Note: `mokutil --help` fails if EFI variables are not supported on the system.
         # If it is impossible to ascertain if the MOK is enrolled in the UEFI, do not add the "_enrolled" suffix to the backup file.
         if command -v mokutil &>/dev/null; then
-		    local mokutil_output=""
-			local mokutil_exit_status=0
-			mokutil_output=$(sudo mokutil --test-key "${PUBLIC_KEY_DIR}/${KEYNAME}.der" 2>&1)
-			mokutil_exit_status="$?"
+            local mokutil_output=""
+            local mokutil_exit_status=0
+            mokutil_output=$(sudo mokutil --test-key "${PUBLIC_KEY_DIR}/${KEYNAME}.der" 2>&1)
+            mokutil_exit_status="$?"
 
-			if [[ "$mokutil_exit_status" -eq 1 ]]; then
-				KEY_SUFFIX="${KEY_SUFFIX}_enrolled"
-			elif [[ "$mokutil_exit_status" -ne 0 ]]; then
-			    echo "$mokutil_output"
-				echo -e "${BOLD_YELLOW_TEXT}WARNING:${CLEAR_TEXT} FAILED TO CHECK CERTIFICATE ENROLLMENT STATUS."
-				echo "Failed to query whether the existing public key (certificate) at '${PUBLIC_KEY_DIR}/${KEYNAME}.der' is already enrolled."
-				echo "Proceeding without appending '_enrolled' to key pair backup."
-			fi
-		fi
+            if [[ "$mokutil_exit_status" -eq 1 ]]; then
+                KEY_SUFFIX="${KEY_SUFFIX}_enrolled"
+            elif [[ "$mokutil_exit_status" -ne 0 ]]; then
+                echo "$mokutil_output"
+                echo -e "${BOLD_YELLOW_TEXT}WARNING:${CLEAR_TEXT} FAILED TO CHECK CERTIFICATE ENROLLMENT STATUS."
+                echo "Failed to query whether the existing public key (certificate) at '${PUBLIC_KEY_DIR}/${KEYNAME}.der' is already enrolled."
+                echo "Proceeding without appending '_enrolled' to key pair backup."
+            fi
+        fi
 
         # Rename the existing public key with the conflicting name.
         sudo mv "${PUBLIC_KEY_DIR}/${KEYNAME}.der" "${PUBLIC_KEY_DIR}/${KEYNAME}.der.${KEY_SUFFIX}.bak"
@@ -222,11 +259,11 @@ function backup_existing_key_pair() {
     fi
 }
 
-function create_new_keypair() {
+function create_new_key_pair() {
     echo "CREATING NEW KEY PAIR..."
 
     # Prepare an OpenSSL command to generate the key pair.
-    local keypair_generation_command=(
+    local key_pair_generation_command=(
         "openssl req"                                     # Request new certificate
         "-x509"                                           # X.509 certificate type
         "-new"                                            # New key pair
@@ -243,7 +280,7 @@ function create_new_keypair() {
 
     # Execute the key pair generation command within the 'akmods' group context.
     # Ensure 'rw-rwx---' permissions.
-    sudo sg akmods -c "umask 037 && ${keypair_generation_command[*]}"
+    sudo sg akmods -c "umask 037 && ${key_pair_generation_command[*]}"
 }
 
 function set_key_permissions() {
@@ -261,6 +298,8 @@ function set_key_permissions() {
 function update_key_symlinks() {
     sudo ln -nsf "${PUBLIC_KEY_DIR}/${KEYNAME}.der" "$PUBLIC_KEY_PATH"
     sudo ln -nsf "${PRIVATE_KEY_DIR}/${KEYNAME}.priv" "$PRIVATE_KEY_PATH"
+	sudo chown -h root:akmods "$PUBLIC_KEY_PATH"
+	sudo chown -h root:akmods "$PRIVATE_KEY_PATH"
 }
 
 # SCRIPT MAINLINE
@@ -279,18 +318,18 @@ create_ca_cert_config
 # Avoid overwriting key pairs with the same randomly-generated name.
 backup_existing_key_pair
 
-# Create new keypair.
-create_new_keypair
+# Create new key pair.
+create_new_key_pair
 
 # Set permissions and sanitise keys.
 set_key_permissions
 
-# Update symlink to use new keypair.
+# Update symlink to use new key pair.
 update_key_symlinks
 
 # Print completion messages.
-echo -e "${BOLD_GREEN_TEXT}SUCCESS!${CLEAR_TEST}"
-echo "Public Key (Certificate) created at:    ${PUBLIC}/${KEYNAME}.der"
+echo -e "\n${BOLD_GREEN_TEXT}SUCCESS!${CLEAR_TEXT}"
+echo "Public Key (Certificate) created at:    ${PUBLIC_KEY_DIR}/${KEYNAME}.der"
 echo "Private Key created at:                 ${PRIVATE_KEY_DIR}/${KEYNAME}.priv"
 echo -e "\nSymlinks:"
 echo "${KEYNAME}.der     -->    ${PUBLIC_KEY_PATH}"
