ensure to build for grub or systemd-boot default kernel
Original patch from <maps-fedorabugzilla@makhmetov.ru>

Adapted to work with grubby as default
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

diff --git a/akmods b/akmods
--- a/akmods
+++ b/akmods
@@ -165,11 +165,6 @@ init ()
 	if [[ ! -n "${kernels}" ]] ; then
 		kernels="$(uname -r)"
 	fi
-	# ensure to build for grub default kernel
-	default_kernel=$(grubby --default-kernel | sed -e 's/^.*vmlinuz-//')
-	if ! $(echo "${kernels}" | grep -q "${default_kernel}") ; then
-		kernels="${kernels} ${default_kernel}"
-	fi
 
 	# we get the echo_{success,failure} stuff from there
 	if [[ -r /etc/rc.d/init.d/functions ]] ; then
@@ -188,6 +183,27 @@ init ()
 			echo -ne " [WARNING]\r"
 			return 1
 		}
+	fi
+
+	# ensure to build for grub or systemd-boot default kernel
+	#
+	# IMPORTANT: "bootctl is-installed" check that systemd-boot is installed only.
+	# It doesn't check if systemd-boot is the default loader.
+	# So we assume grubby results if available
+	if command -v grubby >/dev/null 2>&1 ; then
+		default_kernel=$(grubby --default-kernel | sed -e 's/^.*vmlinuz-//')
+	elif bootctl is-installed >/dev/null 2>&1 ; then
+		# Leave jq as optional - isDefault requires systemd 253
+		if command -v jq >/dev/null ; then
+			default_kernel="$(bootctl list  --json=short | jq  '.[] | select(.isDefault).version')"
+		fi
+	else # They use neither systemd-boot nor grub2
+		echo -n "Unable to figure out the default kernel" >&2
+		echo_warning ; echo
+		default_kernel=""
+	fi
+	if ! $(echo "${kernels}" | grep -q "${default_kernel}") ; then
+		kernels="${kernels} ${default_kernel}"
 	fi
 
 	# needs root permissions
